services:
  postgres:
    image: postgres:15 
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser       
      POSTGRES_PASSWORD: mypassword 
      POSTGRES_DB: myexpense       
    ports:
      - "5432:5432" # Expose port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data in a volume

volumes:
  postgres_data:
